/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'test_CM7_0' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Infineon::CMSIS Driver:VIO:Board&KIT_T2G-B-H_LITE@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_KIT_T2G-B-H_LITE
/* Infineon::Device:Startup@1.0.0 */
#define CMSIS_device_header "cy_device.h"
/* Keil::Network&MDK:CORE@8.1.0 */
#define RTE_Network_Core                /* Network Core */
/* Keil::Network&MDK:Interface:ETH@8.1.0 */
#define RTE_Network_Interface_ETH_0     /* Network Interface ETH 0 */

/* Keil::Network&MDK:Socket:TCP@8.1.0 */
#define RTE_Network_Socket_TCP          /* Network Socket TCP */
/* Keil::Network&MDK:Socket:UDP@8.1.0 */
#define RTE_Network_Socket_UDP          /* Network Socket UDP */


#endif /* RTE_COMPONENTS_H */
