/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0+p49-g56da53bc
 *
 * Project: 'test_CM0p+Target_1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* Infineon::CMSIS Driver:VIO:Board&KIT_T2G-B-H_LITE@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_KIT_T2G-B-H_LITE
/* Infineon::Device:Startup@1.0.0 */
#define CMSIS_device_header "cy_device.h"


#endif /* RTE_COMPONENTS_H */
