/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'test_CM7_0+Target_1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS Driver Validation:Ethernet@1.4.0 */
#define RTE_CMSIS_DV_ETH        /* Driver Validation Ethernet enabled */
/* ARM::CMSIS Driver Validation:Framework@2.0.0 */
#define RTE_CMSIS_DV_PACK_VER   "3.0.0"
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Infineon::CMSIS Driver:VIO:Board&KIT_T2G-B-H_LITE@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_KIT_T2G-B-H_LITE
/* Infineon::Device:Startup@1.0.0 */
#define CMSIS_device_header "cy_device.h"


#endif /* RTE_COMPONENTS_H */
